# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test1.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setup_ui(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(576, 407)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.test_LB = QtWidgets.QLabel(self.centralwidget)
        self.test_LB.setGeometry(QtCore.QRect(240, 60, 91, 81))
        self.test_LB.setObjectName("test_LB")
        self.xinchao_BT = QtWidgets.QPushButton(self.centralwidget)
        self.xinchao_BT.setGeometry(QtCore.QRect(120, 190, 161, 71))
        self.xinchao_BT.setObjectName("xinchao_BT")
        self.tambiet_BT = QtWidgets.QPushButton(self.centralwidget)
        self.tambiet_BT.setGeometry(QtCore.QRect(300, 190, 171, 71))
        self.tambiet_BT.setObjectName("tambiet_BT")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 576, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.test_LB.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:28pt;\">hello</span></p></body></html>"))
        self.xinchao_BT.setText(_translate("MainWindow", "xin chao"))
        self.tambiet_BT.setText(_translate("MainWindow", "tam biet"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setup_ui(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
