# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GDND_python.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1135, 922)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.text_label = QtWidgets.QLabel(self.centralwidget)
        self.text_label.setGeometry(QtCore.QRect(150, -40, 61, 201))
        self.text_label.setObjectName("text_label")
        self.zo_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.zo_pushButton.setGeometry(QtCore.QRect(670, 640, 361, 191))
        self.zo_pushButton.setObjectName("zo_pushButton")
        self.out_pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.out_pushButton_2.setGeometry(QtCore.QRect(120, 680, 75, 23))
        self.out_pushButton_2.setObjectName("out_pushButton_2")
        self.out_pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.out_pushButton_3.setGeometry(QtCore.QRect(110, 780, 75, 23))
        self.out_pushButton_3.setObjectName("out_pushButton_3")
        self.out_pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.out_pushButton_4.setGeometry(QtCore.QRect(970, 70, 75, 23))
        self.out_pushButton_4.setObjectName("out_pushButton_4")
        self.out_pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.out_pushButton_5.setGeometry(QtCore.QRect(960, 170, 75, 23))
        self.out_pushButton_5.setObjectName("out_pushButton_5")
        self.text_label_2 = QtWidgets.QLabel(self.centralwidget)
        self.text_label_2.setGeometry(QtCore.QRect(530, 10, 261, 201))
        self.text_label_2.setObjectName("text_label_2")
        self.ho_textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.ho_textEdit.setGeometry(QtCore.QRect(60, 90, 301, 71))
        self.ho_textEdit.setObjectName("ho_textEdit")
        self.ten_textEdit_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.ten_textEdit_2.setGeometry(QtCore.QRect(530, 230, 301, 71))
        self.ten_textEdit_2.setObjectName("ten_textEdit_2")
        self.ket_qua_label = QtWidgets.QLabel(self.centralwidget)
        self.ket_qua_label.setGeometry(QtCore.QRect(10, 360, 1061, 211))
        self.ket_qua_label.setObjectName("ket_qua_label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1135, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.text_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Họ</span></p></body></html>"))
        self.zo_pushButton.setText(_translate("MainWindow", "ho va ten"))
        self.out_pushButton_2.setText(_translate("MainWindow", "out"))
        self.out_pushButton_3.setText(_translate("MainWindow", "out"))
        self.out_pushButton_4.setText(_translate("MainWindow", "out"))
        self.out_pushButton_5.setText(_translate("MainWindow", "out"))
        self.text_label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:72pt;\">Tên</span></p><p><br/></p></body></html>"))
        self.ket_qua_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:72pt; font-weight:600; font-style:italic; text-decoration: underline; color:#ff5500;\">kết quả</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
